const data = [
    {
        technicalSkills: [
            { skill: 'Ansible' },
            { skill: 'AWS' },
            { skill: 'DevOps' },
            // { skill: 'CloudOps' },
            // { skill: 'CI/CD' },
            { skill: 'Github Actions' },
            { skill: 'DataDog' },
            { skill: 'Docker' },
            // { skill: 'ElasticSearch' },
            { skill: 'Git' },
            { skill: 'Helm' },
            { skill: 'Javascript' },
            { skill: 'Jest' },
            // { skill: 'Jira' },
            { skill: 'Kubernetes' },
            { skill: 'Linux' },
            // { skill: 'Laravel' },
            { skill: 'MySQL' },
            { skill: 'Nginx' },
            { skill: 'Node.js' },
            { skill: 'Terraform' },
            // { skill: 'TDD' },
            { skill: 'Shell scripting' },
            { skill: 'Redis' },
        ],
        conceptualSkills: [
            { skill: 'Infrastructure Architecture Design' },
            { skill: 'Cloud Architecture Design' },
            { skill: 'Solution Architecture Design' },
            // { skill: 'CQRS' },
            { skill: 'Microservices & Decomposition + Arch Patterns' },
            // { skill: 'Event-sourcing' },
            { skill: 'Caching' },
            // { skill: 'Message-queues' },
            // { skill: 'Jump-box' },
            { skill: 'Shell Scripting' },
            // { skill: 'Cron' },
            // { skill: 'ETL' },
            // { skill: 'Data Mining' },
            { skill: 'Data Warehousing' },
        ],
    },
    {
        technicalSkills: [
            { skill: 'AWS' },
            { skill: 'MongoDB' },
            // { skill: 'Firebase' },
            // { skill: 'Google Cloud Platform' },
            // { skill: 'DevOps' },
            { skill: 'CloudOps' },
            // { skill: 'CI/CD' },
            // { skill: 'Github Actions' },
            { skill: 'Docker' },
            { skill: 'Javascript' },
            // { skill: 'Nginx' },
            // { skill: 'Linux' },
            // { skill: 'Git' },
            // { skill: 'Socket.io' },
            { skill: 'Node.js' },
            // { skill: 'MySQL' },
            // { skill: 'Laravel' },
            { skill: 'TDD' },
            // { skill: 'Jest' },
            // { skill: 'Chai' },
            // { skill: 'Mocha' },
            // { skill: 'Sentry' },
            { skill: 'Redis' },
            // { skill: 'Slack-hooks' },
            // { skill: 'Jira' },
        ],
        conceptualSkills: [
            { skill: 'Infrastructure Architecture Design' },
            { skill: 'Cloud Architecture Design' },
            { skill: 'Solution Architecture Design' },
            // { skill: 'CQRS' },
            { skill: 'Microservices & Decomposition + Arch Patterns' },
            // { skill: 'Event-sourcing' },
            { skill: 'Caching' },
            // { skill: 'Message-queues' },
            // { skill: 'Jump-box' },
            { skill: 'Shell Scripting' },
            // { skill: 'Cron' },
            // { skill: 'ETL' },
            // { skill: 'Data Mining' },
            { skill: 'Data Warehousing' },
        ],
    },
    {
        technicalSkills: [
            { skill: 'AWS' },
            { skill: 'MongoDB' },
            // { skill: 'Firebase' },
            // { skill: 'Google Cloud Platform' },
            // { skill: 'DevOps' },
            // { skill: 'CloudOps' },
            { skill: 'CI/CD' },
            // { skill: 'Github Actions' },
            // { skill: 'Docker' },
            // { skill: 'Javascript' },
            { skill: 'Nginx' },
            // { skill: 'Linux' },
            // { skill: 'Git' },
            // { skill: 'Socket.io' },
            { skill: 'Node.js' },
            // { skill: 'MySQL' },
            // { skill: 'Laravel' },
            { skill: 'TDD' },
            // { skill: 'Jest' },
            // { skill: 'Chai' },
            // { skill: 'Mocha' },
            // { skill: 'Sentry' },
            { skill: 'Redis' },
            // { skill: 'Slack-hooks' },
            // { skill: 'Jira' },
        ],
        conceptualSkills: [
            // { skill: 'Infrastructure Architecture Design' },
            { skill: 'Cloud Architecture Design' },
            // { skill: 'Solution Architecture Design' },
            // { skill: 'CQRS' },
            { skill: 'Microservices & Decomposition + Arch Patterns' },
            // { skill: 'Event-sourcing' },
            { skill: 'Caching' },
            // { skill: 'Message-queues' },
            // { skill: 'Jump-box' },
            { skill: 'Shell Scripting' },
            // { skill: 'Cron' },
            // { skill: 'ETL' },
            // { skill: 'Data Mining' },
            { skill: 'Data Warehousing' },
        ],
    },
    {
        technicalSkills: [
            { skill: 'NodeJS' },
            { skill: 'MongoDB' },
            { skill: 'MS SQL' },
            // { skill: 'Azure Data Studio' },
            // { skill: 'Google Cloud Platform' },
            { skill: 'AWS' },
            // { skill: 'Bull MQ' },
            // { skill: 'CI/Linux (Debian)' },
            { skill: 'CI/CD' },
            // { skill: 'Github' },
            { skill: 'Nginx' },
            { skill: 'Redis' },
            // { skill: 'OpenSSL' },
            // { skill: 'Github Actions' },
            // { skill: 'AWS S3 Standard' },
            // { skill: 'AWS EC2' },
            { skill: 'Socket.io' },
            // { skill: 'Node.js' },
            { skill: 'Express' },
            { skill: "PostgreSQL" },
            // { skill: "PG Admin" },
            { skill: "TypeScript" },
            // { skill: "Go Lang" },
            // { skill: "Docker" },
            // { skill: "Hasura" },
            // { skill: "GraphQL" },
            { skill: 'TDD' },
            // { skill: "Jest" },
            { skill: 'React (Functional)' },
            // { skill: 'HTML5 (+ Browser APIs)' },
            // { skill: 'Service Workers' },
            { skill: 'Express' },
            // { skill: 'Workbench' },
            { skill: 'MySQL' },
            // { skill: 'AWS RDS' },
            // { skill: 'AWS Route53' },
            // { skill: 'AWS Amplify' },
            { skill: 'Vapor' },
            // { skill: 'Bull MQ' },
            { skill: 'Redis' },
            // { skill: 'OpenSSL' },
            // { skill: 'Github Actions' },
            // { skill: 'AWS S3 Standard' },
            // { skill: 'AWS EC2' },
            // { skill: 'CSS' },
            // { skill: 'WordPress' },
        ],
        conceptualSkills: [
            { skill: 'SSH Proxy / Reverse Shell' },
            // { skill: 'Jump-box' },
            { skill: 'Shell Scripting' },
            // { skill: 'Cron' },
            // { skill: 'ETL' },
            // { skill: 'Data Mining' },
            { skill: 'Data Warehousing' },
        ],
    },
    {
        technicalSkills: [
            'Angular 2+ (8-11)',
            'RxJS',
            'NgRX',
            'NodeJS',
            'HTML5 (+ Browser APIs)',
            'Service Workers',
            'Express',
            'Socket.io',
            'MongoDB',
            'Mongoose',
            'Atlas Full Text Search',
            'WebRTC',
            'WebAssembly',
            'Browser Media APIs',
            'Bull MQ',
            'CSS',
            'SCSS',
            'Nginx',
            'Redis',
            'OpenSSL',
            'Github Actions',
            'AWS Route53',
            'AWS S3 Standard',
            'AWS EC2',
        ],
        skills: [
            'SSH Proxy / Reverse Shell',
            'Bastion',
            'Shell Scripting',
            'Cron',
            'Full-text Search',
            'Multi-Tenancy',
        ]
    },
    {
        toosls: [
            'Angular 2+ (8-9)',
            'RxJS',
            'React',
            'NgRX',
            'NodeJS',
            'HTML5 (+ Browser APIs)',
            'Service Workers',
            'Express',
            'Socket.io',
            'MongoDB',
            'Mongoose',
            'Atlas Full Text Search',
            'WebRTC',
            'WebAssembly',
            'Browser Media APIs',
            'Bull MQ',
            'CSS',
            'SCSS',
            'Nginx',
            'Redis',
            'OpenSSL',
            'Github Actions',
            'AWS Route53',
            'AWS S3 Standard',
            'AWS EC2',
            'STUN',
            'TURN',
            'Media Gateway',
            'VoxImplant',
            'Wordpress',
            'PHP',
        ],
        skills: [
            'SSH Proxy / Reverse Shell',
            'Bastion',
            'Shell Scripting',
            'Cron',
            'System Administration'
        ]
    }
]

