export const exp = [
    {
        companyName: '433 Football (CloudPrimero x 433)',
        servedAs: [
            {
                position: 'Engineering Lead - Backend',
                duration: '07/2022 - To Date'
            },
            {
                position: 'Senior Backend Engineer',
                duration: '05/2022 - To Date'
            },
        ],
        duration: '05/2022 - To Date',
        companyProfile: '433 Football is one of the largest football communities accross the globe working on Football News, IoT and Data Analytics. (Outsourced via CloudPrimero B.V)',
        uri: 'https://www.433football.com/',
        projects: [
            {
                name: '433 Pro (Formerly Jogo.ai)',
                detail: 'A mapping of the Jogo.ai product to the 433 Football platform.',
                tools: [
                    'NodeJS',
                    'Laravel',
                    'AWS Lambda Functions',
                    'AWS S3 Standard',
                    'AWS EC2',
                    'AWS CodeDeploy',
                    'Service Workers',
                    'Express',
                    'Workbench',
                    'MySQL',
                    'AWS RDS',
                    'Bull MQ',
                    'Linux (Debian)',
                    'Nginx',
                    'Redis',
                    'Github Actions',
                ],
                skills: [
                    'SSH Proxy / Reverse Shell',
                    'Data Mining',
                    'ACID',
                    'Jump-box',
                    'Shell Scripting',
                    'Cron',
                    'Serverless',
                    'OAuth',
                    'Migrations'
                ]
            },
            {
                name: '433 CMS',
                detail: 'CMS for Home of Football',
                tools: [
                    'NodeJS',
                    'AWS Lambda Functions',
                    'AWS S3 Standard',
                    'AWS ElastiCache',
                    'AWS EC2',
                    'AWS CodeDeploy',
                    'AWS Elastic Transcoder',
                    'Redis Stack',
                    'Service Workers',
                    'Express',
                    'AWS RDS',
                    'Bull MQ',
                    'Linux (Debian)',
                    'Nginx',
                    'Redis',
                    'Github Actions',
                ],
                skills: [
                    'SSH Proxy / Reverse Shell',
                    'Data Mining',
                    'Data Redundancy',
                    'BASE / ACID',
                    'Jump-box',
                    'Shell Scripting',
                    'Cron',
                    'Serverless',
                    'OAuth',
                    'Migrations'
                ]
            },
            {
                name: '433 Home of Football Backend',
                detail: 'Backend applications and infrastructure for the 433 HoF app, coupled with the 433 CMS',
            }
        ],
        technicalSkills: [
            { skill: 'AWS' },
            { skill: 'MongoDB Atlas' },
            { skill: 'Firebase' },
            { skill: 'Google Cloud Platform' },
            { skill: 'DevOps' },
            { skill: 'CloudOps' },
            { skill: 'CI/CD' },
            { skill: 'Github Actions' },
            { skill: 'Docker' },
            { skill: 'Javascript' },
            { skill: 'Nginx' },
            { skill: 'Linux' },
            { skill: 'Git' },
            { skill: 'Socket.io' },
            { skill: 'Node.js' },
            { skill: 'MySQL' },
            { skill: 'Laravel' },
            { skill: 'Jest' },
            { skill: 'Chai' },
            { skill: 'Mocha' },
            { skill: 'Sentry' },
            { skill: 'Redis' },
            { skill: 'Slack-hooks' },
            { skill: 'Jira' },
        ],
        conceptualSkills: [
            { skill: 'Infrastructure Architecture Design' },
            { skill: 'Cloud Architecture Design' },
            { skill: 'Solution Architecture Design' },
            { skill: 'CQRS' },
            { skill: 'Microservices' },
            { skill: 'Event-sourcing' },
            { skill: 'Caching' },
            { skill: 'Message-queues' },
            { skill: 'Message-queues' },
            { skill: 'Jump-box' },
            { skill: 'Shell Scripting' },
            { skill: 'Cron' },
            { skill: 'ETL' },
            { skill: 'Data Mining' },
            { skill: 'Data Warehousing' },
        ],
        tasksAchievements: [
            'Helped the App & Infra to scale and 1Million+ users till BREAKPOINT, under a quarter\'s period',
            'Expanded legacy 433Pro (formerly Jogo.ai) to new NodeJS backend while offering data aggregation pipelines.',
            'Helped ship faster APIs with 5x reduced average response times',
            'Increased API throughoputs by 8x',
            'Helped optimize DB Queries & Schemas to reduce query times by 27x',
            'Helped enhance and integrate a proper Version Control Strategy & Flow for team Backend',
        ]
    },
    {
        companyName: 'Liquid Technologies',
        servedAs: [
            {
                position: 'Consultant Senior Software Engineer',
                duration: '05/2022 - 06/2022',
            },
            {
                position: 'Team Lead: Engineering & Architecture',
                duration: '09/2021 - 05/2022',
            }
        ],
        companyProfile: 'Liquid Technology provides engineering solutions for corporates, encompassing data-science, embedded & software solutions.',
        uri: 'https://www.liqteq.com/',
        technicalSkills: [
            { skill: 'NodeJS' },
            { skill: 'MongoDB MS SQL' },
            { skill: 'Azure Data Studio' },
            { skill: 'Google Cloud Express' },
            { skill: 'AWS RDS' },
            { skill: 'Bull MQ' },
            { skill: 'CI/Linux (Debian)' },
            { skill: 'Github Nginx' },
            { skill: 'Redis' },
            { skill: 'OpenSSL' },
            { skill: 'Github Actions' },
            { skill: 'AWS S3 Standard' },
            { skill: 'AWS EC2' },
            { skill: 'Socket.io' },
            { skill: 'Node.js' },
            { skill: "PostgreSQL" },
            { skill: "PG Admin" },
            { skill: "TypeScript" },
            { skill: "Go Lang" },
            { skill: "Docker" },
            { skill: "Hasura" },
            { skill: "GraphQL" },
            { skill: "Google Cloud Platform" },
            { skill: "Firebase" },
            { skill: "Jest" },
            { skill: 'React (Functional)' },
            { skill: 'HTML5 (+ Browser APIs)' },
            { skill: 'Service Workers' },
            { skill: 'Express' },
            { skill: 'Workbench' },
            { skill: 'MySQL' },
            { skill: 'AWS RDS' },
            { skill: 'AWS Route53' },
            { skill: 'AWS Amplify' },
            { skill: 'Vapor' },
            { skill: 'Bull MQ' },
            { skill: 'Redis' },
            { skill: 'OpenSSL' },
            { skill: 'Github Actions' },
            { skill: 'AWS S3 Standard' },
            { skill: 'AWS EC2' },
            { skill: 'CSS' },
            { skill: 'Nginx' },
            { skill: 'WordPress' },
            { skill: 'Linux (Debian)' },
        ],
        conceptualSkills: [
            { skill: 'SSH Proxy / Reverse Shell' },
            { skill: 'Jump-box' },
            { skill: 'Shell Scripting' },
            { skill: 'Cron' },
            { skill: 'ETL' },
            { skill: 'Data Mining' },
            { skill: 'Data Warehousing' },
        ],
        projects: [
            {
                name: 'TGS - Cedar AI API',
                detail: 'A Node.JS API triggering an ETL pipeline to extract information and map to OLAP Databases',
                tools: [
                    'NodeJS',
                    'MS SQL',
                    'Azure Data Studio',
                    'Express',
                    'AWS RDS',
                    'Bull MQ',
                    'Linux (Debian)',
                    'Nginx',
                    'Redis',
                    'OpenSSL',
                    'Github Actions',
                    'AWS S3 Standard',
                    'AWS EC2',
                ],
                skills: [
                    'SSH Proxy / Reverse Shell',
                    'Jump-box',
                    'Shell Scripting',
                    'Cron',
                    'ETL',
                    'Data Mining',
                    'Data Warehousing',
                ]
            },
            {
                name: 'Hiki',
                detail: 'A Social platrform for the Autistic community',
                tools: [
                    'NodeJS',
                    'PostgreSQL',
                    'PG Admin',
                    'TypeScript',
                    'Go Lang',
                    'Docker',
                    'Hasura',
                    'GraphQL',
                    'Google Cloud Platform',
                    'Firebase',
                    'Jest',
                ],
                skills: [
                    'SSH Proxy / Reverse Shell',
                    'Jump-box',
                    'Shell Scripting',
                    'Cron',
                    'ETL',
                    'Data Mining',
                    'Data Warehousing'
                ]
            },
            {
                name: 'SmartRupee',
                detail: 'A smart financing calculator and investment tool for B2B & B2C usage.',
                tools: [
                    'NodeJS',
                    'Socket.io',
                    'React (Functional)',
                    'HTML5 (+ Browser APIs)',
                    'Service Workers',
                    'Express',
                    'Workbench',
                    'MySQL',
                    'AWS RDS',
                    'AWS Route53',
                    'AWS Amplify',
                    'Vapor',
                    'Bull MQ',
                    'Redis',
                    'OpenSSL',
                    'Github Actions',
                    'AWS S3 Standard',
                    'AWS EC2',
                    'CSS',
                    'Nginx',
                    'WordPress',
                    'Linux (Debian)',
                ],
                skills: [
                    'SSH Proxy / Reverse Shell',
                    'Jump-box',
                    'Shell Scripting',
                    'Cron',
                ]
            },
            {
                name: 'TGS Employee Portal (HRM & Operations)',
                detail: 'An on-prem HRM & Operations maangement system for Trans Global International.',
                tools: [
                    'React (Functional)',
                    'NodeJS',
                    'HTML5 (+ Browser APIs)',
                    'Service Workers',
                    'Express',
                    'Socket.io',
                    'PgAdmin',
                    'PostgresSQL',
                    'Sequelize',
                    'Linux',
                    'CSS',
                    'Nginx',
                    'Redis',
                    'OpenSSL',
                    'Github Actions',
                ],
                skills: [
                    'SSH Proxy / Reverse Shell',
                    'Bastion',
                    'Shell Scripting',
                    'Cron',
                ]
            },
            {
                name: 'Vidan',
                detail: 'An Computer Vision based Analytics SaaS for a predefined & custom KPIs',
                tools: [
                    'React (Functional)',
                    'NodeJS',
                    'HTML5 (+ Browser APIs)',
                    'Service Workers',
                    'Express',
                    'Socket.io',
                    'MongoDB',
                    'Mongoose',
                    'Bull MQ',
                    'CSS',
                    'SCSS',
                    'Nginx',
                    'Redis',
                    'OpenSSL',
                    'Linux',
                ],
                skills: [
                    'SSH Proxy / Reverse Shell',
                    'Bastion',
                    'Shell Scripting',
                    'Cron',
                    'Multi-Tenancy',
                ]
            }
        ],
        tasksAchievements: [
            'Onboarded and provided System & Architecture solutions to  IoT related data problems in Procheck (Sarmayakaar Funded Platform)',
            'Streamlined the delivery of SmartRupee, an Elphinsotne Platform as a Consultant Engineering Lead',
            'Setup company boilerplates for Programme & People Management',
            'Setup, designed infrastructures and Architectures of Applications large scale platforms & products with my team',
            'Introduced Scrum + Extreme Programming Practices',
            'Introduced the use of Atlassian Products such as Jira and Confluence',
            'Improved Version Control Strategies and Practices',
            'Setup and deployed boilerplates for CI/CD Pipelines',
            'Trained and onboarded Developers, Engineers, QA Engineers (Automation + Testing) and DevOps Engineers',
            'Aligned with Data-Engineers & Data Analysts (Data Team) to provide robust solutions and designed architecture for one of their upcoming products'
        ]
    },
    {
        servedAs: 'Full-Stack Team Lead, Architect, Scrum Master',
        companyName: 'Digitest.nl',
        duration: '09/2019 - 09/2021',
        companyProfile: ' Digitest is an online assessment and examination SaaS solution. A KBenP partner firm',
        uri: 'http://digitest.nl/',
        projects: [
            {
                name: 'Digitest',
                detail: 'An online assessment SaaS Solution acquired by KBenP, maintained by GWorkPlace and team Digitest',
                tools: [
                    'Angular 2+ (8-11)',
                    'RxJS',
                    'NgRX',
                    'NodeJS',
                    'HTML5 (+ Browser APIs)',
                    'Service Workers',
                    'Express',
                    'Socket.io',
                    'MongoDB',
                    'Mongoose',
                    'Atlas Full Text Search',
                    'WebRTC',
                    'WebAssembly',
                    'Browser Media APIs',
                    'Bull MQ',
                    'CSS',
                    'SCSS',
                    'Nginx',
                    'Redis',
                    'OpenSSL',
                    'Github Actions',
                    'AWS Route53',
                    'AWS S3 Standard',
                    'AWS EC2',
                ],
                skills: [
                    'SSH Proxy / Reverse Shell',
                    'Bastion',
                    'Shell Scripting',
                    'Cron',
                    'Full-text Search',
                    'Multi-Tenancy',
                ]
            }
        ],
        technicalSkills: [],
        conceptualSkills: [],
        tasksAchievements: [
            'Designed extremely high throughput ingestion APIs with high availability and less than 500ms response times for C10K.',
            'Enhanced Aggregation Pipelines for MongoDB to increase database performance and reduce query resolution times for ~4 seconds to about ~120ms.',
            'Looked over and integrated clever design patterns to make application modules plug and play, adaptable, reusable and replaceable.',
            'Served as Full Stack MEAN Developer, Team Lead & Assosciate Architect.',
            'Managed DevOps and served as Co-Dev Manager.',
            'Leading development for the product Digitest, which is an online testing System.',
            'Helped manage product requirements',
            'Lead entirety of features production',
            'Played the role of Scrum Master while managing the Backlog as well as the team',
            'Maintained Shift left SDLC.',
            'Implemented and maintained basic principles such as SOLID, DRY-KISS, WET-KISS depending on usecases.',
        ]
    },
    {
        servedAs: 'Product Development Lead',
        companyName: 'Scientise7 Pvt. ltd',
        duration: '09/2019 - 12/2020',
        companyProfile: 'A company carrying multiple mature products that are live, providing quality solutions in record time.',
        uri: '',
        projects: [
            //     {
            //         name: 'Scientise',
            //         detail: '...',
            //         tools: [
            //             'Angular 2+ (8-9)',
            //             'RxJS',
            //             'React',
            //             'NgRX',
            //             'NodeJS',
            //             'HTML5 (+ Browser APIs)',
            //             'Service Workers',
            //             'Express',
            //             'Socket.io',
            //             'MongoDB',
            //             'Mongoose',
            //             'Atlas Full Text Search',
            //             'WebRTC',
            //             'WebAssembly',
            //             'Browser Media APIs',
            //             'Bull MQ',
            //             'CSS',
            //             'SCSS',
            //             'Nginx',
            //             'Redis',
            //             'OpenSSL',
            //             'Github Actions',
            //             'AWS Route53',
            //             'AWS S3 Standard',
            //             'AWS EC2',
            //             'STUN',
            //             'TURN',
            //             'Media Gateway',
            //             'VoxImplant',
            //             'Wordpress',
            //             'PHP',
            //         ],
            //         skills: [
            //             'SSH Proxy / Reverse Shell',
            //             'Bastion',
            //             'Shell Scripting',
            //             'Cron',
            //             'System Administration'
            //         ]
            //     }
        ],
        technicalSkills: [],
        conceptualSkills: [],
        tasksAchievements: [
            // 'Served as Scrum Master on multiple products.',
            // 'Provided Solution Architectures for several projects.',
            // 'Lead production of 2 live international products including Hikma Online & Digitest Netherlands.',
            // 'Managed rapid development pipeline for custom projects & requests.',
            // 'Requriements engineering for products.',
            // 'Product Management & Development including managing scurm backlogs.',
            // 'Automated CI/CD pipelines design & management.',
            // 'Design and integration of Produce-Test-Package-Release-Ship pipeline for fast deliveries.'
        ]
    },
    {
        servedAs: 'Team Lead (Senior Software Engineer)',
        companyName: 'Pulsate Technologies',
        duration: '05/2018 - 06/2019',
        companyProfile: 'Pulsate Technologies (Pulsatechs) is a tech company aimed at upgrading the standard of living for an increasingly technological society.',
        uri: '',
        projects: [
            //     {
            //         name: '...',
            //         detail: '...',
            //         tools: [],
            //         skills: [
            //             'SSH Proxy / Reverse Shell',
            //             'Jump-box',
            //             'Bastion',
            //             'Shell Scripting',
            //             'Cron',
            //         ]
            //     }
        ],
        technicalSkills: [],
        conceptualSkills: [],
        tasksAchievements: [
            // 'Head of Development for their products, \'Pluto\'.',
            // 'Designed highly scalable and secure IoT systems, powered by Raspberry Pi, Arduino & NodeJS.',
            // 'Provided software solutions to multiple factories and SMEs in Karachi.'
        ]
    },
    {
        servedAs: 'Electrical Engineer & IoT Developer',
        companyName: 'Integraject',
        duration: '07/2015 - 11/2016',
        companyProfile: 'A service based company providing full-stack development & IoT consultancy as services.',
        uri: '',
        projects: [
        ],
        technicalSkills: [],
        conceptualSkills: [],
        tasksAchievements: [
            // 'Part of Development team for their first product, \'AutoSocket\'.',
            // 'Went through extreme technical growth in that period, gaining hands-on experience with multiple tools & technologies.',
            // 'Worked on Varsity Maps, an application deployed in Indian River State College.'
        ]
    }
]
