export const skills = [
    { skill: 'AWS EC2', level: 'senior' },
    { skill: 'AWS ALB / NLB (Load Balancer)', level: 'intermediate' },
    { skill: 'AWS EC2 Auto-scaling', level: 'intermediate' },
    { skill: 'AWS SQS', level: 'intermediate' },
    { skill: 'AWS Lambda', level: 'intermediate' },
    { skill: 'AWS SDK', level: 'intermediate' },
    { skill: 'AWS CLI', level: 'intermediate' },
    { skill: 'AWS S3 Standard', level: 'intermediate' },
    { skill: 'AWS Route53', level: 'intermediate' },
    { skill: 'AWS SNS', level: 'intermediate' },
    { skill: 'AWS SES', level: 'intermediate' },
    { skill: 'AWS RDS', level: 'intermediate' },
    { skill: 'AWS DynamoDB', level: 'intermediate' },
    { skill: 'AWS X-Ray', level: 'raw' },
    { skill: 'AWS API Gateway', level: 'raw' },
    { skill: 'AWS CloudWatch', level: 'raw' },
    { skill: 'AWS CloudFront', level: 'raw' },
    { skill: 'Amazon CloudFront', level: 'raw' },
    { skill: 'MongoDB Atlas', level: 'senior' },
    { skill: 'MongoDB Analysis, Scaling & Optimizations', level: 'senior' },
    { skill: 'Mongo Atlas Search', level: 'senior' },
    { skill: 'Firebase', level: 'intermediate' },
    { skill: 'Google Cloud Platform', level: 'raw' },
    { skill: 'DevOps', level: 'intermediate' },
    { skill: 'CloudOps', level: 'intermediate' },
    { skill: 'Infrastructure Architecture Design', level: 'intermediate' },
    { skill: 'Cloud Architecture Design', level: 'intermediate' },
    { skill: 'Solution Architecture Design', level: 'intermediate' },
    { skill: 'Product Management', level: 'intermediate' },
    { skill: 'Project Management', level: 'senior' },
    { skill: 'Jenkins', level: 'raw' },
    { skill: 'CI/CD', level: 'intermediate' },
    { skill: 'Github Actions', level: 'intermediate' },
    { skill: 'Research & Dev', level: 'senior' },
    { skill: 'Docker', level: 'raw' },
    { skill: 'Scrum', level: 'senior' },
    { skill: 'Jira Software', level: 'intermediate' },
    { skill: 'System Administration', level: 'intermediate' },
    { skill: 'ES5', level: 'senior' },
    { skill: 'ES6', level: 'senior' },
    { skill: 'NextGen JS', level: 'senior' },
    { skill: 'OOP', level: 'senior' },
    { skill: 'Version Control Systems (Git, SVN)', level: 'intermediate' },
    { skill: 'RxJS', level: 'senior' },
    { skill: 'Web Sockets', level: 'senior' },
    { skill: 'Socket.IO', level: 'senior' },
    { skill: 'IoT', level: 'senior' },
    { skill: 'Linux - CentOS, Raspbian, Ubuntu', level: 'senior' },
    { skill: 'Server Management & Setup', level: 'senior' },
    { skill: 'MQTT', level: 'raw' },
    { skill: 'Stateless & Stateful Design', level: 'senior' },
    { skill: 'JWT', level: 'senior' },
    { skill: 'NodeJS Design Patterns', level: 'senior' },
    { skill: 'Oracle SQL+', level: 'intermediate' },
    { skill: 'MySQL', level: 'senior' },
    { skill: 'MariaDB', level: 'senior' },
    { skill: 'ACID + Serialization', level: 'intermediate' },
    { skill: 'BASE', level: 'senior' },
    { skill: 'SOLID', level: 'senior' },
    { skill: 'DRY-WET-KISS', level: 'senior' },
    { skill: 'System Design', level: 'intermediate' },
    { skill: 'React', level: 'intermediate' },
    { skill: 'Redux', level: 'raw' },
    { skill: 'LDAP', level: 'raw' },
    { skill: 'Active Directory', level: 'raw' },
    { skill: 'Jest', level: 'raw' },
    { skill: 'Cypress', level: 'raw' },
    { skill: 'Mocha', level: 'raw' },
    { skill: 'Chai', level: 'raw' },
    { skill: 'People Management', level: 'intermediate' },
    { skill: 'Programme Management', level: 'intermediate' },
    { skill: 'Python', level: 'raw' },
    { skill: 'Java', level: 'raw' },
]