export const skills = [
    'AWS EC2',
    'AWS S3 Standard',
    'AWS Route53',
    'AWS SNS',
    'AWS SES',
    'AWS ECS',
    'AWS EKS',
    'AWS RDS',
    'AWS DynamoDB',
    'AWS Lambda',
    'Amazon CloudFront',
    'MongoDB',
    'Mongo Atlas Search',
    'AWS EBS',
    'Firebase',
    'Google Cloud Platform',
    'Dialogflow',
    'GCP CloudVision API',
    'DevOps',
    'CloudOps',
    'Platform Architecture Design',
    'Infrastructure Architecture Design',
    'Cloud Architecture Design',
    'Solution Architecture Design',
    'Product Management',
    'Project Management',
    'Jenkins, CI/CD',
    'Github Actions',
    'Research & Dev',
    'Docker',
    'Agile',
    'Scrum',
    'Jira Software',
    'System Administration',
    'Full-stack Web (MEAN)',
    'Full-stack Web (MERN)',
    'Angular 2+ (4-10)',
    'ES5',
    'ES6',
    'NextGen JS',
    'OOP',
    'Version Control Systems (Git, SVN)',
    'RxJS',
    'Android Native',
    'Cordova',
    'Electron',
    'Chrome App & Extension Development',
    'Socket.IO',
    'IoT',
    'Processing.JS & Native Processing',
    'Bootstrap',
    'Angular Material',
    'Material Design',
    'Linux - CentOS, Raspbian, Ubuntu',
    'Server Management & Setup',
    'MQTT',
    'Arduino',
    'Vue JS',
    'Stateless & Stateful Design',
    'JWT',
    'NodeJS Design Patterns',
]