export const skills = [
    { skill: 'AWS EC2', level: 'senior' },
    { skill: 'AWS S3 Standard', level: 'intermediate' },
    { skill: 'AWS Route53', level: 'intermediate' },
    { skill: 'AWS SNS', level: 'intermediate' },
    { skill: 'AWS SES', level: 'intermediate' },
    { skill: 'AWS ECS', level: 'raw' },
    { skill: 'AWS EKS', level: 'raw' },
    { skill: 'AWS RDS', level: 'intermediate' },
    { skill: 'AWS DynamoDB', level: 'intermediate' },
    { skill: 'AWS Lambda', level: 'intermediate' },
    { skill: 'Amazon CloudFront', level: 'intermediate' },
    { skill: 'MongoDB', level: 'senior' },
    { skill: 'Mongo Atlas Search', level: 'senior' },
    { skill: 'AWS EBS', level: 'intermediate' },
    { skill: 'Firebase', level: 'intermediate' },
    { skill: 'Google Cloud Platform', level: 'raw' },
    { skill: 'Dialogflow', level: 'raw' },
    { skill: 'GCP CloudVision API', level: 'raw' },
    { skill: 'DevOps', level: 'intermediate' },
    { skill: 'CloudOps', level: 'intermediate' },
    { skill: 'Platform Architecture Design', level: 'senior' },
    { skill: 'Infrastructure Architecture Design', level: 'intermediate' },
    { skill: 'Cloud Architecture Design', level: 'intermediate' },
    { skill: 'Solution Architecture Design', level: 'intermediate' },
    { skill: 'Product Management', level: 'intermediate' },
    { skill: 'Project Management', level: 'senior' },
    { skill: 'Jenkins', level: 'raw' },
    { skill: 'CI/CD', level: 'intermediate' },
    { skill: 'Github Actions', level: 'intermediate' },
    { skill: 'Research & Dev', level: 'senior' },
    { skill: 'Docker', level: 'raw' },
    { skill: 'Agile', level: 'senior' },
    { skill: 'Scrum', level: 'senior' },
    { skill: 'Jira Software', level: 'intermediate' },
    { skill: 'System Administration', level: 'intermediate' },
    { skill: 'Full-stack Web (MEAN)', level: 'senior' },
    { skill: 'Full-stack Web (MERN)', level: 'senior' },
    { skill: 'Angular 2+ (4-11)', level: 'senior' },
    { skill: 'ES5', level: 'senior' },
    { skill: 'ES6', level: 'senior' },
    { skill: 'NextGen JS', level: 'senior' },
    { skill: 'OOP', level: 'senior' },
    { skill: 'Version Control Systems (Git, SVN)', level: 'intermediate' },
    { skill: 'RxJS', level: 'senior' },
    { skill: 'Android Native', level: 'raw' },
    { skill: 'Cordova', level: 'senior' },
    { skill: 'Electron', level: 'senior' },
    { skill: 'Chrome App & Extension Development', level: 'senior' },
    { skill: 'Socket.IO', level: 'senior' },
    { skill: 'IoT', level: 'senior' },
    { skill: 'Processing.JS', level: 'intermediate' },
    { skill: 'Native Processing', level: 'raw' },
    { skill: 'Bootstrap', level: 'senior' },
    { skill: 'Angular Material', level: 'senior' },
    { skill: 'NgRX', level: 'raw' },
    { skill: 'Material Design', level: 'senior' },
    { skill: 'Linux - CentOS, Raspbian, Ubuntu', level: 'senior' },
    { skill: 'Server Management & Setup', level: 'senior' },
    { skill: 'MQTT', level: 'raw' },
    { skill: 'Arduino', level: 'senior' },
    { skill: 'Vue JS', level: 'raw' },
    { skill: 'Stateless & Stateful Design', level: 'senior' },
    { skill: 'JWT', level: 'senior' },
    { skill: 'NodeJS Design Patterns', level: 'senior' },
    { skill: 'CSS', level: 'senior' },
    { skill: 'SCSS', level: 'intermediate' },
    { skill: 'Oracle SQL+', level: 'intermediate' },
    { skill: 'MySQL', level: 'senior' },
    { skill: 'MariaDB', level: 'senior' },
    { skill: 'ACID + Serialization', level: 'intermediate' },
    { skill: 'BASE', level: 'senior' },
    { skill: 'SOLID', level: 'senior' },
    { skill: 'DRY-WET-KISS', level: 'senior' },
    { skill: 'System Design', level: 'intermediate' },
    { skill: 'React', level: 'intermediate' },
    { skill: 'Redux', level: 'raw' },
    { skill: 'LDAP', level: 'raw' },
    { skill: 'Active Directory', level: 'raw' },
    { skill: 'People Management', level: 'intermediate' },
    { skill: 'Programme Management', level: 'intermediate' },
]